Update read.md and some codes, and images
lumyjuwon/KoreaNewsCrawler pull request #22
Opened 2020-12-13 15:59 UTC by slslslrhfem

2020-12-13 16:09 UTC, slslslrhfem commented
readme file과 image를 수정하였고, sportscrawler.py에서 csv의 순서를 기존 crawler와 일치시켰습니다. 

from korea_news_crawler.sportcrawler import SportCrawler가 올바르게 작동하려면 새로운 Release가 되어야 할 것으로 보이는데, 이에 관해서 저는 아는 것이 없어 우선은 토론 창에 의견을 남겨둡니다.

2020-12-13 16:35 UTC, slslslrhfem commented
아 제가 korea news crawler를 1.50으로 업데이트를 안했었네요.. readme를 조금 더 수정하겠습니다.

2020-12-13 18:13 UTC, slslslrhfem commented
스포츠 크롤러에서 함수 이름이 잘못되어있어 아예 크롤링이 되지 않던 이슈를 발견하여 해결하였고, 이를 해결하는 김에 csv작성을 각 뉴스별로 하도록 구현하여 중간에 코드를 interrupt해도 어느정도 크롤링이 되어있도록 구현했습니다.

그리고 Writer.py 에서 windows 운영체제인 경우만 다른 encoding을 사용하시는데, 이유를 알 수 있을까요? 이로 인해서 csv 작성시 이슈가 생깁니다. 혹시나 별도의 이슈가 있어서 다른 encoding을 사용하는 것이라면, 제가 writer.py를 다시 고치고 스포츠크롤러의 csv작성을 try문으로 작성하겠습니다.

2020-12-13 18:19 UTC, slslslrhfem commented
아.. 이슈를 저도 발견해서 Writer.py는 원래대로 돌려놓고 csv작성을 try문으로 작성했습니다.

2020-12-14 12:18 UTC, slslslrhfem commented on korea_news_crawler/sportcrawler.py
> +                        url = f'{final_url}&page={page}'
여기 부분은 사이트 url에 page=904203395&page=904203396&page=904203397 이런식으로 계속 붙는 이상한 이슈가 있어 url 변수명의 사용이 꼬였다는 판단을 하여 조금 수정했습니다.

2020-12-24 01:02 UTC, lumyjuwon requested changes

2020-12-26 11:37 UTC, slslslrhfem commented on korea_news_crawler/sportcrawler.py
> +                        url = f'{final_url}&page={page}'
total_page = self.get_total_page(url)에서 사용하는 url이 있기 때문에 위 3라인의 코드를 전부 삭제하면 안됩니다.
(위 url의 경우 pagenumber 정보가 없는 url로, append하게 되는 url과 다릅니다.)

final_url변수를 deepcopy해서 사용하는 것은 for문 내에서 url 변수명으로 재선언을 하기때문에 필요합니다.  loop에서 'url'로 사용하고 있는 변수명을 다른 변수명을 사용하는 방법을 통해 final_url 변수를 삭제하는 것도 가능합니다만, 큰 의미가 없는 것 같아 우선은 url을 input_url로 초기화하는 line만 우선 정리하였습니다.

2020-12-26 11:37 UTC, slslslrhfem commented on korea_news_crawler/sportcrawler.py
> +                hefscript = ''
script라는 접미사가 붙는 것들은 CSV 작성에 사용하는 변수들에 script라는 접미사를 사용합니다.  물론 hefscript의 경우 이를 이용해 contents를 불러오기도 하고 하니 CSV 작성에만 사용하지는 않지만, 우선은 CSV 작성에 사용은 하니 script를 붙여서 변수명을 지었던 것 같습니다. 우선 hef_script로 바꾸어 두겠습니다.

2020-12-28 14:24 UTC, lumyjuwon commented on korea_news_crawler/sportcrawler.py
> +                    final_url = copy.deepcopy(url)
```suggestion
                    final_url = f'${input_url}{year}{month}{day}'
```
이렇게 하고 84번, 89번 라인 url 변수 선언한 내용을 지웁니다.

2020-12-28 14:24 UTC, lumyjuwon commented on korea_news_crawler/sportcrawler.py
>                      total_page = self.get_total_page(url)
```suggestion
                    total_page = self.get_total_page(final_url)
```

이렇게 하면 url 변수 scope 문제도 없어져 deepcopy 할 필요도 없지 않을까요 ?

2021-01-01 13:15 UTC, slslslrhfem commented on korea_news_crawler/sportcrawler.py
>                      total_page = self.get_total_page(url)
아 죄송합니다 확인이 늦었네요.  위 내용을 그대로 local에 적용시켜 테스트해본 결과 크롤링이 잘 되었으니 제안해주신 내용으로 commit하는 것이 좋아보입니다.

2021-01-02 05:50 UTC, lumyjuwon commented on korea_news_crawler/sportcrawler.py
> +import copy
```suggestion
```

2021-01-02 05:51 UTC, merged